//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRACNGHIEMBYWINFORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public string MSV { get; set; }
        public decimal password { get; set; }
        public string username { get; set; }
        public string Name { get; set; }
        public Nullable<int> phone { get; set; }
        public Nullable<System.DateTime> dayofbirth { get; set; }
        public string Email { get; set; }
        public int ID { get; set; }
        public string FileName { get; set; }
        public byte[] Image { get; set; }
    }
}
